import {Buffer} from 'node:buffer';
import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import zlib from 'node:zlib';
import sharp from 'sharp';
import {parseInputFile, ensureDir} from './utils.js';
import {wranngleColors} from './colors.js';

export type BrandBookSwatch = {
	name: string;
	hex: string;
};

export type BrandBookTypePairing = {
	heading: string;
	body: string;
};

export type BrandBookOptions = {
	inputFilePath: string;
	outputPath: string;
	brandName: string;
	tagline: string;
	palette: BrandBookSwatch[];
	typePairing: BrandBookTypePairing;
};

type LogoRaster = {
	data: Uint8Array;
	width: number;
	height: number;
};

const pageWidth = 612;
const pageHeight = 792;
const logoSlot = {
	x: 72,
	y: 540,
	width: 200,
	height: 200,
};
const swatchSlot = {
	x: 72,
	y: 280,
	size: 80,
	gap: 16,
};

function hexToRgb(hex: string): [number, number, number] {
	const value = hex.startsWith('#') ? hex.slice(1) : hex;
	const r = Number.parseInt(value.slice(0, 2), 16);
	const g = Number.parseInt(value.slice(2, 4), 16);
	const b = Number.parseInt(value.slice(4, 6), 16);
	return [r, g, b];
}

function pdfColor(hex: string): string {
	const [r, g, b] = hexToRgb(hex);
	const normalise = (channel: number) => (channel / 255).toFixed(3);
	return `${normalise(r)} ${normalise(g)} ${normalise(b)}`;
}

const backslash = String.fromCodePoint(0x5C);

function escapeText(value: string): string {
	return value
		.replaceAll(backslash, backslash + backslash)
		.replaceAll('(', backslash + '(')
		.replaceAll(')', backslash + ')');
}

async function decodeLogoToRgb(inputFilePath: string): Promise<LogoRaster> {
	const buffer = await parseInputFile(inputFilePath);
	const image = sharp(Buffer.from(buffer))
		.resize(400, 400, {fit: 'inside', withoutEnlargement: false})
		.flatten({background: '#ffffff'});
	const {data, info} = await image.removeAlpha().raw().toBuffer({resolveWithObject: true});
	return {data: new Uint8Array(data), width: info.width, height: info.height};
}

function buildContentStream(options: BrandBookOptions, hasLogo: boolean): string {
	const lines = [
		'q',
		`${pdfColor(wranngleColors.night950)} rg`,
		`0 0 ${pageWidth} ${pageHeight} re`,
		'f',
		'Q',
		'BT',
		'/F1 28 Tf',
		`${pdfColor(wranngleColors.sand50)} rg`,
		'72 720 Td',
		`(${escapeText(options.brandName)}) Tj`,
		'ET',
		'BT',
		'/F2 12 Tf',
		`${pdfColor(wranngleColors.sand50)} rg`,
		'72 700 Td',
		`(${escapeText(options.tagline)}) Tj`,
		'ET',
		'BT',
		'/F1 14 Tf',
		`${pdfColor(wranngleColors.sunset500)} rg`,
		'72 660 Td',
		'(Logo) Tj',
		'ET',
	];

	if (hasLogo) {
		lines.push(
			'q',
			`${logoSlot.width} 0 0 ${logoSlot.height} ${logoSlot.x} ${logoSlot.y} cm`,
			'/Logo Do',
			'Q',
		);
	} else {
		lines.push(
			'q',
			`${pdfColor(wranngleColors.sand50)} rg`,
			`${logoSlot.x} ${logoSlot.y} ${logoSlot.width} ${logoSlot.height} re`,
			'f',
			'Q',
		);
	}

	lines.push(
		'BT',
		'/F1 14 Tf',
		`${pdfColor(wranngleColors.sunset500)} rg`,
		'72 460 Td',
		'(Palette) Tj',
		'ET',
	);

	const swatchCount = Math.min(options.palette.length, 5);
	for (let index = 0; index < swatchCount; index++) {
		const swatch = options.palette[index]!;
		const x = swatchSlot.x + (index * (swatchSlot.size + swatchSlot.gap));
		const {y} = swatchSlot;
		lines.push(
			'q',
			`${pdfColor(swatch.hex)} rg`,
			`${x} ${y} ${swatchSlot.size} ${swatchSlot.size} re`,
			'f',
			'Q',
			'BT',
			'/F2 9 Tf',
			`${pdfColor(wranngleColors.sand50)} rg`,
			`${x} ${y - 14} Td`,
			`(${escapeText(swatch.name)}) Tj`,
			'ET',
			'BT',
			'/F2 8 Tf',
			`${pdfColor(wranngleColors.sand50)} rg`,
			`${x} ${y - 24} Td`,
			`(${escapeText(swatch.hex)}) Tj`,
			'ET',
		);
	}

	lines.push(
		'BT',
		'/F1 14 Tf',
		`${pdfColor(wranngleColors.sunset500)} rg`,
		'72 220 Td',
		'(Typography) Tj',
		'ET',
		'BT',
		'/F2 11 Tf',
		`${pdfColor(wranngleColors.sand50)} rg`,
		'72 200 Td',
		`(Heading: ${escapeText(options.typePairing.heading)}) Tj`,
		'ET',
		'BT',
		'/F2 11 Tf',
		`${pdfColor(wranngleColors.sand50)} rg`,
		'72 184 Td',
		`(Body: ${escapeText(options.typePairing.body)}) Tj`,
		'ET',
		'BT',
		'/F2 8 Tf',
		`${pdfColor(wranngleColors.sand50)} rg`,
		'72 96 Td',
		'(Generated by logo_maker brand-book) Tj',
		'ET',
	);

	return lines.join('\n');
}

const resourceFonts = '<< /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >>';

function buildPdf(content: string, logo?: LogoRaster): Uint8Array {
	const compressedContent = new Uint8Array(zlib.deflateSync(Buffer.from(content, 'binary')));
	const compressedLogo = logo ? new Uint8Array(zlib.deflateSync(logo.data)) : undefined;
	const logoObjectIndex = 6;
	const xobjectFragment = logo ? ` /XObject << /Logo ${logoObjectIndex} 0 R >>` : '';
	const resources = `<< /Font ${resourceFonts}${xobjectFragment} >>`;

	const objects = [
		'<< /Type /Catalog /Pages 2 0 R >>',
		'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
		`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources ${resources} /Contents 4 0 R >>`,
		`<< /Length ${compressedContent.length} /Filter /FlateDecode >>\nstream\n${Buffer.from(compressedContent).toString('binary')}\nendstream`,
		'<< /Producer (logo_maker brand-book) /Creator (logo_maker) >>',
	];

	if (logo && compressedLogo) {
		const imageDictionary = [
			'<< /Type /XObject /Subtype /Image',
			`/Width ${logo.width} /Height ${logo.height}`,
			'/ColorSpace /DeviceRGB /BitsPerComponent 8',
			`/Filter /FlateDecode /Length ${compressedLogo.length} >>`,
		].join(' ');
		objects.push(`${imageDictionary}\nstream\n${Buffer.from(compressedLogo).toString('binary')}\nendstream`);
	}

	let body = '%PDF-1.4\n%âãÏÓ\n';
	const offsets: number[] = [];
	for (const [index, object] of objects.entries()) {
		offsets.push(Buffer.byteLength(body, 'binary'));
		body += `${index + 1} 0 obj\n${object}\nendobj\n`;
	}

	const xrefOffset = Buffer.byteLength(body, 'binary');
	let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
	for (const offset of offsets) {
		xref += `${offset.toString().padStart(10, '0')} 00000 n \n`;
	}

	const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 5 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

	return new Uint8Array(Buffer.from(body + xref + trailer, 'binary'));
}

export const defaultPalette: BrandBookSwatch[] = [
	{name: 'Sunset', hex: wranngleColors.sunset500},
	{name: 'Violet', hex: wranngleColors.violet500},
	{name: 'Sand', hex: wranngleColors.sand50},
	{name: 'Night', hex: wranngleColors.night950},
	{name: 'Cactus', hex: wranngleColors.cactusGreen},
];

export const defaultTypePairing: BrandBookTypePairing = {
	heading: 'Inter',
	body: 'Source Sans Pro',
};

export async function generateBrandBook(options: BrandBookOptions): Promise<string> {
	await ensureDir(path.dirname(options.outputPath));

	let logo: LogoRaster | undefined;
	try {
		logo = await decodeLogoToRgb(options.inputFilePath);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.warn(`[WARN] Logo decode skipped: ${message}`);
	}

	const content = buildContentStream(options, Boolean(logo));
	const pdf = buildPdf(content, logo);
	await fs.writeFile(options.outputPath, pdf);
	return options.outputPath;
}

function parseArguments(args: string[]): BrandBookOptions {
	let inputFilePath = path.join(process.cwd(), 'raw', 'logo-data-url.txt');
	let outputPath = path.join(process.cwd(), 'output', 'brand-book.pdf');
	let brandName = 'Wranngle';
	let tagline = 'Brand-In-A-Box';

	for (let index = 0; index < args.length; index++) {
		const argument = args[index]!;
		switch (argument) {
			case '--input': {
				inputFilePath = path.resolve(process.cwd(), args[++index] ?? '');
				break;
			}

			case '--output': {
				outputPath = path.resolve(process.cwd(), args[++index] ?? '');
				break;
			}

			case '--brand': {
				brandName = args[++index] ?? brandName;
				break;
			}

			case '--tagline': {
				tagline = args[++index] ?? tagline;
				break;
			}

			default: {
				if (!argument.startsWith('--')) {
					inputFilePath = path.resolve(process.cwd(), argument);
				}
			}
		}
	}

	return {
		inputFilePath,
		outputPath,
		brandName,
		tagline,
		palette: defaultPalette,
		typePairing: defaultTypePairing,
	};
}

if (import.meta.main) {
	const options = parseArguments(process.argv.slice(2));
	const written = await generateBrandBook(options);
	console.log(`[READY] Brand book written to ${written}`);
}
