import {Buffer} from 'node:buffer';
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {ensureDir} from './utils.js';
import {generateEssentialFavicons} from './generator.js';
import {generateManifest} from './manifest.js';
import {extractPalette, paletteToCss, paletteToJson, type PaletteColor} from './palette.js';
import {recommendPairing, type TypeStyle, type FontPairing} from './types.js';
import {renderOgTemplate} from './og.js';
import {generateBrandBook, type BrandBookSwatch} from './brand-book.js';
import {wranngleColors} from './colors.js';

export type KitOptions = {
	name: string;
	color: string;
	outDir: string;
	typeStyle?: TypeStyle;
	ogTemplate?: string;
};

export type KitStepStatus = 'ok' | 'skipped' | 'failed';

export type KitStepResult = {
	step: string;
	artifact: string;
	status: KitStepStatus;
	note?: string;
};

export type KitManifest = {
	name: string;
	slug: string;
	color: string;
	typeStyle: TypeStyle;
	ogTemplate: string;
	steps: KitStepResult[];
};

const hexRe = /^#([0-9a-fA-F]{6})$/;

export function slugify(name: string): string {
	const lowered = name.toLowerCase();
	const collapsed = lowered.replaceAll(/[^a-z0-9]+/gv, '-');
	const trimmed = collapsed.replace(/^-+|-+$/gv, '');
	return trimmed || 'kit';
}

export function normalizeHex(input: string): string {
	const trimmed = input.trim();
	const withHash = trimmed.startsWith('#') ? trimmed : `#${trimmed}`;
	if (!hexRe.test(withHash)) {
		throw new Error(`--color requires a 6-digit hex (got: ${input})`);
	}

	return withHash.toLowerCase();
}

function escapeXml(value: string): string {
	return value
		.replaceAll('&', '&amp;')
		.replaceAll('<', '&lt;')
		.replaceAll('>', '&gt;')
		.replaceAll('"', '&quot;')
		.replaceAll('\'', '&apos;');
}

function hexToRgb(hex: string): [number, number, number] {
	const value = hex.startsWith('#') ? hex.slice(1) : hex;
	return [
		Number.parseInt(value.slice(0, 2), 16),
		Number.parseInt(value.slice(2, 4), 16),
		Number.parseInt(value.slice(4, 6), 16),
	];
}

function pickInkColor(hex: string): string {
	const [r, g, b] = hexToRgb(hex);
	const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
	return luminance > 0.55 ? wranngleColors.night950 : wranngleColors.sand50;
}

export function renderWordmarkSvg(name: string, color: string): string {
	const ink = pickInkColor(color);
	const safeName = escapeXml(name);
	const fontSize = Math.max(48, Math.min(160, Math.floor(512 / Math.max(name.length, 1) * 1.6)));
	return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <rect width="1024" height="1024" fill="${color}"/>
  <text x="512" y="540" text-anchor="middle" dominant-baseline="middle"
        font-family="Inter, system-ui, sans-serif" font-weight="700"
        font-size="${fontSize}" fill="${ink}">${safeName}</text>
</svg>
`;
}

async function writeReadme(outDir: string, manifest: KitManifest, palette: PaletteColor[], pairing: FontPairing): Promise<void> {
	const rows = manifest.steps
		.map(s => `| \`${s.artifact}\` | ${s.status} | ${s.note ?? ''} |`)
		.join('\n');
	const paletteRows = palette
		.map((c, i) => `- \`brand-${i + 1}\` — ${c.hex}`)
		.join('\n');
	const body = `# ${manifest.name} identity kit

Generated by \`logo-maker kit\`. Deterministic for the same name + color.

- **Seed color:** \`${manifest.color}\`
- **Type pairing:** ${pairing.heading} (heading) / ${pairing.body} (body)
- **OG template:** ${manifest.ogTemplate}

## Artifacts

| File | Status | Note |
|---|---|---|
${rows}

## Palette

${paletteRows}

## How to use

- Drop \`favicon.ico\` and \`icon-*.png\` into your web root.
- Embed \`og.png\` as the \`og:image\` meta tag.
- Hand \`brand-book.pdf\` to designers and clients.
- Use \`palette.json\` and \`type-pairing.json\` as machine-readable inputs for
  downstream tooling.
`;
	await fs.writeFile(path.join(outDir, 'README.md'), body);
}

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

export async function runKit(options: KitOptions): Promise<KitManifest> {
	const slug = slugify(options.name);
	const outDir = path.join(options.outDir, slug);
	await ensureDir(outDir);

	const color = normalizeHex(options.color);
	const typeStyle: TypeStyle = options.typeStyle ?? 'sans';
	const ogTemplate = options.ogTemplate ?? 'minimal';
	const steps: KitStepResult[] = [];

	const logoSvgPath = path.join(outDir, 'logo.svg');
	const logoPngPath = path.join(outDir, 'logo.png');
	const palettePath = path.join(outDir, 'palette.json');
	const paletteCssPath = path.join(outDir, 'palette.css');
	const typePairingPath = path.join(outDir, 'type-pairing.json');
	const ogPath = path.join(outDir, 'og.png');
	const brandBookPath = path.join(outDir, 'brand-book.pdf');

	const svg = renderWordmarkSvg(options.name, color);
	await fs.writeFile(logoSvgPath, svg);
	steps.push({step: 'wordmark', artifact: 'logo.svg', status: 'ok'});

	let logoPngBuffer: Buffer | undefined;
	try {
		logoPngBuffer = await sharp(Buffer.from(svg)).resize(1024, 1024, {fit: 'contain'}).png().toBuffer();
		await fs.writeFile(logoPngPath, logoPngBuffer);
		steps.push({step: 'png', artifact: 'logo.png', status: 'ok'});
	} catch (error) {
		steps.push({step: 'png', artifact: 'logo.png', status: 'failed', note: errorMessage(error)});
	}

	if (logoPngBuffer) {
		try {
			await generateEssentialFavicons(new Uint8Array(logoPngBuffer), outDir);
			steps.push({step: 'favicons', artifact: 'favicon.ico', status: 'ok'});
			await generateManifest(outDir, {
				name: options.name,
				shortName: options.name,
				themeColor: color,
				backgroundColor: wranngleColors.night950,
			});
			steps.push({step: 'manifest', artifact: 'site.webmanifest', status: 'ok'});
		} catch (error) {
			steps.push({step: 'favicons', artifact: 'favicon.ico', status: 'failed', note: errorMessage(error)});
		}
	} else {
		steps.push({step: 'favicons', artifact: 'favicon.ico', status: 'skipped', note: 'logo.png missing'});
	}

	let palette: PaletteColor[] = [];
	if (logoPngBuffer) {
		const seedPath = path.join(outDir, '.kit-seed.png');
		try {
			await fs.writeFile(seedPath, logoPngBuffer);
			palette = await extractPalette(seedPath, 5);
			await fs.writeFile(palettePath, paletteToJson(palette));
			await fs.writeFile(paletteCssPath, paletteToCss(palette));
			steps.push({step: 'palette', artifact: 'palette.json', status: 'ok'});
		} catch (error) {
			steps.push({step: 'palette', artifact: 'palette.json', status: 'failed', note: errorMessage(error)});
		} finally {
			await fs.unlink(seedPath).catch(() => undefined);
		}
	} else {
		steps.push({step: 'palette', artifact: 'palette.json', status: 'skipped', note: 'logo.png missing'});
	}

	const pairing = recommendPairing(typeStyle);
	try {
		const payload = {style: typeStyle, ...pairing};
		await fs.writeFile(typePairingPath, `${JSON.stringify(payload, undefined, 2)}\n`);
		steps.push({step: 'type-pairing', artifact: 'type-pairing.json', status: 'ok'});
	} catch (error) {
		steps.push({step: 'type-pairing', artifact: 'type-pairing.json', status: 'failed', note: errorMessage(error)});
	}

	if (logoPngBuffer) {
		try {
			const buffer = await renderOgTemplate(ogTemplate, new Uint8Array(logoPngBuffer));
			await fs.writeFile(ogPath, buffer);
			steps.push({step: 'og', artifact: 'og.png', status: 'ok'});
		} catch (error) {
			steps.push({step: 'og', artifact: 'og.png', status: 'failed', note: errorMessage(error)});
		}
	} else {
		steps.push({step: 'og', artifact: 'og.png', status: 'skipped', note: 'logo.png missing'});
	}

	if (logoPngBuffer) {
		const seedPath = path.join(outDir, '.kit-brand-seed.png');
		try {
			await fs.writeFile(seedPath, logoPngBuffer);
			const swatches: BrandBookSwatch[] = palette.length > 0
				? palette.map((c, i) => ({name: `brand-${i + 1}`, hex: c.hex}))
				: [{name: 'Primary', hex: color}];
			await generateBrandBook({
				inputFilePath: seedPath,
				outputPath: brandBookPath,
				brandName: options.name,
				tagline: `${options.name} identity kit`,
				palette: swatches,
				typePairing: {heading: pairing.heading, body: pairing.body},
			});
			steps.push({step: 'brand-book', artifact: 'brand-book.pdf', status: 'ok'});
		} catch (error) {
			steps.push({step: 'brand-book', artifact: 'brand-book.pdf', status: 'failed', note: errorMessage(error)});
		} finally {
			await fs.unlink(seedPath).catch(() => undefined);
		}
	} else {
		steps.push({step: 'brand-book', artifact: 'brand-book.pdf', status: 'skipped', note: 'logo.png missing'});
	}

	const manifest: KitManifest = {
		name: options.name,
		slug,
		color,
		typeStyle,
		ogTemplate,
		steps,
	};
	await writeReadme(outDir, manifest, palette, pairing);
	steps.push({step: 'readme', artifact: 'README.md', status: 'ok'});

	const manifestPath = path.join(outDir, 'kit.json');
	await fs.writeFile(manifestPath, `${JSON.stringify(manifest, undefined, 2)}\n`);

	return manifest;
}
